version: '3'
services:
  online-shop-mysql:
    image: mysql:5.6
    container_name: online-shop-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: "online-shop"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "online-shop"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
  online-shop-backend:
    build: ./
    container_name: online-shop-backend
    volumes:
      - ./app:/src
    ports:
      - 3000:3000
    depends_on:
      - online-shop-mysql
  online-shop-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - online-shop-mysql:db
    ports:
        - 8080:80
    environment:
        MYSQL_USER: online-shop
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root